### ISSUE TITLE
[Yenepoya] UAT feedback for reports

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#88]
Map report is giving error - https://docs.google.com/spreadsheets/d/1gbEK3KCA9LN9HayFqBh66XCJxKiy3C_AUoNlF8topGU/edit#gid=1450362073
Report - Households with Individuals with history of fever in last 15 days
Filter - Suevellience Unit - RHCDC

Report feedback - 
- Households with Individuals with history of fever in last 15 days
> Gives error message
- Report - Self Reported Morbidity
> Add row 93 and 103 (https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428)
> The term 'family' in the Indicator should be replaced by 'households' 
> The term 'heart disease' can be replaced by 'coronary artery disease' in the chronic illness report
> Remove Indicators COLD and LOW BACK PAIN from Acute illness
- Report - Health Seeking Behaviour 
(https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428)
> Change the Government and health facility based on report and options in the question.
- Report - Selfcare practices in Diabetes Mellitus
> Indicators - Number and proportion diabetic females of population with >88cm waist circumference - Denominator should be Total `female` enrolled in DM 
Number and proportion of diabetic males of population with >102 cm waist circumference - Denominator should be Total `Male` enrolled in DM 
- Report - NCD Age Group -
> https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1465272386
> Add Gender also in this report.
- Antenatal and Postnatal cases - 
> Correct the spelling of the indicator- bad obsteric history to bad obstetric history.
> Proportion of mothers with institutional delivery: in the formula- denominator should be total women delivered.
> Proportion of mothers utilized sevices under JSY- denominator should be- Delivered and Eligible for JSY is YES
> Proportion of mothers utilized sevices under JSSK- denominator should be- Delivered and Eligible for JSSK is YES
- Antenatal cases - followup
> Indicators - `Mothers received second doses of TT  during present pregnancy` and `Mothers received second doses of TT  during present pregnancy`. Doses should be dose.
- Line list of women with Abortion.
> Add column "No of abortions in the past" form Pregnancy enrolment form

**Comment by 1t5j0y** [comment]
1. 'Households with Individuals with history of fever in last 15 days' map report
- [x] Error when location filters applied

2. 'Self Reported Morbidity' aggregate report
- [x] Add row 93 and 103
- [x] The term 'family' in the Indicator should be replaced by 'households'
- [x] The term 'heart disease' can be replaced by 'coronary artery disease' in the chronic illness report
- [x] Remove Indicators COLD and LOW BACK PAIN from Acute illness

3. Report - Health Seeking Behaviour 
- [ ] Change the Government and health facility based on report and options in the question. (Pending #87)

4. Report - Selfcare practices in Diabetes Mellitus
- [x] Indicators - Number and proportion diabetic females of population with >88cm waist circumference - Denominator should be Total female enrolled in DM
- [x] Number and proportion of diabetic males of population with >102 cm waist circumference - Denominator should be Total Male enrolled in DM 

5. Report - NCD Age Group
- [x] Add Gender also in this report.

6. Antenatal and Postnatal cases
- [x] Correct the spelling of the indicator- bad obsteric history to bad obstetric history.
- [ ] ~Proportion of mothers with institutional delivery: in the formula- denominator should be total women delivered.~
--The report was already only picking up women for whom pregnancy outcome form was filled up. No change made.
- [ ] Proportion of mothers utilized sevices under JSY- denominator should be- Delivered and Eligible for JSY is YES (Pending #87)
- [ ] Proportion of mothers utilized sevices under JSSK- denominator should be- Delivered and Eligible for JSSK is YES (Pending #87)

7. Antenatal cases - followup
- [x] Indicators - `Mothers received second doses of TT during present pregnancy` and `Mothers received second doses of TT during present pregnancy`. Doses should be dose.

8. Line list of women with Abortion.
- [x] Add column "No of abortions in the past" form Pregnancy enrolment form

**Comment by 1t5j0y** [comment]
Following changes (dependent on #87) are pending:
- Report - Health Seeking Behaviour
-- Change the Government and health facility based on report and options in the question.
- Report - Antenatal and Postnatal cases
-- Proportion of mothers utilized sevices under JSY- denominator should be- Delivered and Eligible for JSY is YES
-- Proportion of mothers utilized sevices under JSSK- denominator should be- Delivered and Eligible for JSSK is YES

`yenepoya_household_survey_view` and `yenepoya_pregnancy_outcome_form_view` have been updated to include the newly introduced form fields for these reports.

**Comment by garimadosar5** [comment]
QA Notes - 
**Self Reported Morbidity**
- Row "Any" in Chronic sickness should be sum of all the chronic sickness. but it is not matching.
- Row "Any" should be more than the total of all acute illnesses. so it should be more than 10.
- "NO" in chronic sickness and Acute illness - Replace this with without chronic sickness.
**Individual Socio Demographic profile**
- Total population more than 60 years to be changed to Total population aged 60 years and above .
**Environmental factor**
- Households with toilet construction was done by support from external agency (Govt/Private) `Change this to` Households with toilet constructed with  support from Govt/Private agency.

**Comment by 1t5j0y** [comment]
1. Self Reported Morbidity
- [ ] Row "Any" in Chronic sickness should be sum of all the chronic sickness. but it is not matching. 
No change made as this is a multiselect and sum will not match.
- [ ] Row "Any" should be more than the total of all acute illnesses. so it should be more than 10.
Similar to previous
- [x] "NO" in chronic sickness and Acute illness - Replace this with without chronic sickness.
2. Individual Socio Demographic profile
- [x] Total population more than 60 years to be changed to Total population aged 60 years and above .
3. Environmental factor
- [x] Households with toilet construction was done by support from external agency (Govt/Private) Change this to Households with toilet constructed with support from Govt/Private agency.
